// Package all imports all the commands
package all

import (
	// Active commands
	_ "cmd"
	_ "cmd/authorize"
	_ "cmd/cat"
	_ "cmd/check"
	_ "cmd/cleanup"
	_ "cmd/config"
	_ "cmd/copy"
	_ "cmd/copyto"
	_ "cmd/dedupe"
	_ "cmd/delete"
	_ "cmd/genautocomplete"
	_ "cmd/gendocs"
	_ "cmd/listremotes"
	_ "cmd/ls"
	_ "cmd/lsd"
	_ "cmd/lsl"
	_ "cmd/md5sum"
	_ "cmd/memtest"
	_ "cmd/mkdir"
	_ "cmd/mount"
	_ "cmd/move"
	_ "cmd/moveto"
	_ "cmd/obscure"
	_ "cmd/purge"
	_ "cmd/rmdir"
	_ "cmd/rmdirs"
	_ "cmd/sha1sum"
	_ "cmd/size"
	_ "cmd/sync"
	_ "cmd/version"
)
